name: PR Checks

on:
  pull_request:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  # Essential checks for PRs
  essential:
    name: Essential Checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true

    - name: Check workspace
      run: cargo check --workspace

    - name: Run tests
      run: cargo test --workspace

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy --workspace -- -D warnings

    - name: Build release
      run: cargo build --release --workspace

    - name: Security audit
      run: |
        cargo install cargo-audit
        cargo audit
